# Generated by Django 5.2.7 on 2025-10-21 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_brand_options_brand_slug_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
