# Generated by Django 5.2.6 on 2025-10-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_customers', models.PositiveIntegerField(default=0)),
                ('new_customers', models.PositiveIntegerField(default=0)),
                ('repeat_customers', models.PositiveIntegerField(default=0)),
                ('active_customers', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Customer Summary',
                'verbose_name_plural': 'Customer Summaries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='InventorySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_stock', models.PositiveIntegerField(default=0)),
                ('in_stock_items', models.PositiveIntegerField(default=0)),
                ('low_stock_items', models.PositiveIntegerField(default=0)),
                ('out_of_stock_items', models.PositiveIntegerField(default=0)),
                ('on_delivery', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Inventory Summary',
                'verbose_name_plural': 'Inventory Summaries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SalesSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('completed_orders', models.PositiveIntegerField(default=0)),
                ('pending_orders', models.PositiveIntegerField(default=0)),
                ('processing_orders', models.PositiveIntegerField(default=0)),
                ('canceled_orders', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sales Summary',
                'verbose_name_plural': 'Sales Summaries',
                'ordering': ['-date'],
            },
        ),
    ]
