# Generated by Django 5.2.6 on 2025-10-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('reserved_quantity', models.PositiveIntegerField(default=0, help_text='Quantity reserved for pending orders')),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('batch_number', models.CharField(blank=True, help_text='Batch/Lot number for traceability', max_length=50, null=True)),
                ('low_stock_threshold', models.PositiveIntegerField(default=5)),
                ('reorder_quantity', models.PositiveIntegerField(default=10, help_text='Quantity to reorder when stock is low')),
                ('last_restocked', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventories',
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock'), ('over_stock', 'Over Stock')], max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out'), ('return', 'Return'), ('damaged', 'Damaged')], max_length=20)),
                ('quantity', models.IntegerField(help_text='Positive for in/return, negative for out/damaged')),
                ('reference', models.CharField(blank=True, help_text='Order number, adjustment reason, etc.', max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('previous_quantity', models.PositiveIntegerField(editable=False)),
                ('new_quantity', models.PositiveIntegerField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
